#!/usr/bin/env python3
# 
# Cross Platform and Multi Architecture Advanced Binary Emulation Framework
#

from unicorn.riscv_const import *

reg_map = {
	"zero": UC_RISCV_REG_ZERO,
	"ra": UC_RISCV_REG_RA,
	"sp": UC_RISCV_REG_SP,
	"gp": UC_RISCV_REG_GP,
	"tp": UC_RISCV_REG_TP,
	"t0": UC_RISCV_REG_T0,
	"t1": UC_RISCV_REG_T1,
	"t2": UC_RISCV_REG_T2,
	"s0": UC_RISCV_REG_S0,
	"fp": UC_RISCV_REG_FP,
	"s1": UC_RISCV_REG_S1,
	"a0": UC_RISCV_REG_A0,
	"a1": UC_RISCV_REG_A1,
	"a2": UC_RISCV_REG_A2,
	"a3": UC_RISCV_REG_A3,
	"a4": UC_RISCV_REG_A4,
	"a5": UC_RISCV_REG_A5,
	"a6": UC_RISCV_REG_A6,
	"a7": UC_RISCV_REG_A7,
	"s2": UC_RISCV_REG_S2,
	"s3": UC_RISCV_REG_S3,
	"s4": UC_RISCV_REG_S4,
	"s5": UC_RISCV_REG_S5,
	"s6": UC_RISCV_REG_S6,
	"s7": UC_RISCV_REG_S7,
	"s8": UC_RISCV_REG_S8,
	"s9": UC_RISCV_REG_S9,
	"s10": UC_RISCV_REG_S10,
	"s11": UC_RISCV_REG_S11,
	"t3": UC_RISCV_REG_T3,
	"t4": UC_RISCV_REG_T4,
	"t5": UC_RISCV_REG_T5,
	"t6": UC_RISCV_REG_T6,
	"ft0": UC_RISCV_REG_FT0,
	"ft1": UC_RISCV_REG_FT1,
	"ft2": UC_RISCV_REG_FT2,
	"ft3": UC_RISCV_REG_FT3,
	"ft4": UC_RISCV_REG_FT4,
	"ft5": UC_RISCV_REG_FT5,
	"ft6": UC_RISCV_REG_FT6,
	"ft7": UC_RISCV_REG_FT7,
	"fs0": UC_RISCV_REG_FS0,
	"fs1": UC_RISCV_REG_FS1,
	"fa0": UC_RISCV_REG_FA0,
	"fa1": UC_RISCV_REG_FA1,
	"fa2": UC_RISCV_REG_FA2,
	"fa3": UC_RISCV_REG_FA3,
	"fa4": UC_RISCV_REG_FA4,
	"fa5": UC_RISCV_REG_FA5,
	"fa6": UC_RISCV_REG_FA6,
	"fa7": UC_RISCV_REG_FA7,
	"fs2": UC_RISCV_REG_FS2,
	"fs3": UC_RISCV_REG_FS3,
	"fs4": UC_RISCV_REG_FS4,
	"fs5": UC_RISCV_REG_FS5,
	"fs6": UC_RISCV_REG_FS6,
	"fs7": UC_RISCV_REG_FS7,
	"fs8": UC_RISCV_REG_FS8,
	"fs9": UC_RISCV_REG_FS9,
	"fs10": UC_RISCV_REG_FS10,
	"fs11": UC_RISCV_REG_FS11,
	"ft8": UC_RISCV_REG_FT8,
	"ft9": UC_RISCV_REG_FT9,
	"ft10": UC_RISCV_REG_FT10,
	"ft11": UC_RISCV_REG_FT11,
	"pc": UC_RISCV_REG_PC,
}
