version: 2.1

#orbs:
#  win: circleci/windows@2.2.0

jobs:
#  linux:
#    docker:
#      - image: circleci/python:3.9-buster
#    steps:
#      - checkout
#      - run:
#          name: "Install qiling framework"
#          command: |
#            python -m virtualenv env
#            . env/bin/activate
#            pip install .
#            cd examples/rootfs/x86_linux/kernel
#            unzip -P infected m0hamed_rootkit.ko.zip
#      - run:
#          name: "Run linux test"
#          command: |
#            . env/bin/activate
#            cd tests
#            ./test_elf.sh

#  windows:
#    machine:
#      image: windows-server-2019-vs2019:stable
#    resource_class: windows.medium
#    steps:
#      - checkout
#      - run:
#          name: "Disable defender and setup python"
#          command: |
#            powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"
#            powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"
#            powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
#            nuget install python -Version 3.6.8 -ExcludeVersion -OutputDirectory .
#            ./python/tools/python.exe -m pip install virtualenv
#            ./python/tools/python.exe -m virtualenv env
#      - run:
#          name: "Install qiling framework"
#          shell: powershell
#          command: |
#            env\Scripts\activate.ps1
#            pip install setuptools wheel
#            pip install .
#            .\examples\scripts\dllscollector.bat
#            cd examples\rootfs\x86_windows\bin
#            unzip -Pinfected wannacry.bin.zip
#            unzip -Pinfected UselessDisk.bin.zip
#            unzip -Pinfected GandCrab502.bin.zip
#            unzip -Pinfected al-khaser.bin.zip
#            unzip -Pinfected sality.dll.zip
#      - run:
#          name: "Run win test"
#          shell: powershell
#          command: |
#            env\Scripts\activate.ps1
#            cd tests
#            .\test_pe.bat

  macos:
    macos:
      xcode: 10.1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      MACOSX_DEPLOYMENT_TARGET: 10.13.6
    steps:
      - checkout
      - run:
          name: "Install wget"
          command: |
            brew install wget cmake

      - restore_cache:
          keys:
            - python-{{ .Environment.CIRCLE_JOB }}-3.7.0-macos-10.13.6

      - run: 
          name: "Install qiling framework"
          command: |
            pip3 install --upgrade pip
            pip3 install wheel setuptools
            pip3 install .
            ./examples/scripts/dylibcollector.sh
            cd examples/rootfs/x8664_macos/kext
            unzip -Pinfected SuperRootkit.kext.zip

      - save_cache:
          paths:
            - ~/Library/Caches/pip
          key: python-{{ .Environment.CIRCLE_JOB }}-3.7.0-macos-10.13.6

      - run:
          name: "Run macos test"
          command: |
             cd tests
             ./test_macho.sh


workflows:
  version: 2
  run-tests:
    jobs:
      - macos
