#!/usr/bin/env python3
# 
# Cross Platform and Multi Architecture Advanced Binary Emulation Framework
#

from qiling.os.const import *
from .fncc import winsdkapi

LOCALE_T = INT
ULONG = PARAM_INTN
CCHAR = PARAM_INT8
CHAR = PARAM_INT8
UCHAR = PARAM_INT16
USHORT = PARAM_INT16
SHORT = PARAM_INT16

PUNICODE_STRING = WSTRING
PCUNICODE_STRING = WSTRING
WCHAR = PARAM_INT16
BOOLEAN = INT
# BOOL = 8
# STRING_ADDR = 9
# WSTRING_ADDR = 10
# GUID = 11

# Workarounds:
PCANSI_STRING = STRING
PANSI_STRING = STRING
PCSZ = STRING
# PWSTR = WSTRING
PCWSTR = WSTRING
